apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ template "reflector-sample.fullname" $ }}-cert
  annotations:
    reflector.v1.k8s.emberstack.com/secret-reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/secret-reflection-allowed-namespaces: "default"
spec:
  secretName: {{ template "reflector-sample.fullname" $ }}-secret-certificate
  issuerRef:
    name: {{ template "reflector-sample.fullname" $ }}-someissuer
    kind: ClusterIssuer
  dnsNames:
  - '*.dev.winromulus.com'