apiVersion: v1
kind: Secret
metadata:
  name: {{ template "reflector-sample.fullname" . }}-secret-auto
  labels:
    app.kubernetes.io/name: {{ include "reflector-sample.name" . }}
    helm.sh/chart: {{ include "reflector-sample.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ""
type: Opaque
data:
  apikey:  {{ "somevalue" | b64enc | quote }}