apiVersion: v1
kind: Secret
metadata:
  name: {{ template "reflector-sample.fullname" . }}-secret-certificate
  labels:
    app.kubernetes.io/name: {{ include "reflector-sample.name" . }}
    helm.sh/chart: {{ include "reflector-sample.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data: {}