{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "reflector.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "reflector.name" . }}
    helm.sh/chart: {{ include "reflector.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["watch", "list"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["list"]
  - apiGroups: ["certmanager.k8s.io"]
    resources: ["certificates", "certificates/finalizers"]
    verbs: ["watch"]
  - apiGroups: ["cert-manager.io"]
    resources: ["certificates", "certificates/finalizers"]
    verbs: ["watch"]
{{- end }}
